.\" Manpage for em302_process
.\" Contact jgnistad@gmail.com to correct errors or typos.
.TH em302_process 1 "31 July 2015" "1.0" "em302_process man page"

.SH NAME
\fBem302_process\fP \- Process Kongsberg EM302 multibeam bathymetry data collected by CCGS Amundsen

.SH VERSION
Version 1.0

.SH SYNOPSIS
\fBem302_process\fP [\fB-A -B -C\fP \fB\-D\fIcolortable\fP \fB\-E\fIdatalist\fP -H \fB\-M\fIdatalist\fP \fB-P\fIdatalist\fP \fB-T\fInmeafile\fP \fB-U\fP]

.SH DESCRIPTION
em302_process is a high-level bash shell script used to process EM302 multibeam bathymetry data collected by the Canadian ice-breaker CCGS Amundsen. em302_process works in unison with a parameters file called \fIparameters.dat\fP. This file must reside at the same level as the em302_process bash script. The \fIparameters.dat\fP file provides file location and file naming conventions in order to run em302_process. Make sure to fully read the content of the \fIparameters.dat\fP file before executing em302_process.

em302_process is a front-end to \fBMB-System\fP and some python scripts specifically written to produce the two fundamental datasets of the Canadian Arctic Mapping program: 15'x30' basemap tiles in ESRI Grids (.EHdr) format and 15'x30' maps in GIF format.

.SH AUTHORSHIP
Jean-Guy Nistad (jgnistad@gmail.com)
.br
  Freelance
.br
Gabriel Joyal (gabriel.joyal.1@ulaval.ca)
.br
  Laval University
.br
Patrick Lajeunesse (patrick.lajeunesse@ggr.ulaval.ca)
.br
  Laval University
  
.SH OPTIONS
.TP
.B \-A
Creates a \fBMB-System\fP tide file from the \fBWebTide\fP file \fITrack Elevation Prediction (Time in GMT).html\fP located in the directory pointed to by the variable $DIR_WEBTIDE (see \fIparameters.dat\fP file), and stores it in the directory pointed to be the variable $DIR_MB_TIDE (see \fIparameters.dat\fP file).

.TP
.B \-B
Creates a \fBCARIS HIPS & SIPS\fP tide file from the \fBWebTide\fP file \fITrack Elevation Prediction (Time in GMT).html\fP located in the directory pointed to by the variable $DIR_WEBTIDE (see \fIparameters.dat\fP file), and stores it in the directory pointed to be the variable $DIR_HIPS_TIDE (see \fIparameters.dat\fP file).

.TP
.B \-C
Converts all .all files contained in the directory pointed to by the variable $DIR_DATA_ALL (see \fIparameters.dat\fP file) into .mb59 files and stores them into the directory pointed to by the variable $DIR_DATA_MB59 (see \fIparameters.dat\fP file). For each .all file, the program will try to find a .gsf file with the same name in the directory pointed to by the variable $DIR_DATA_GSF (see \fIparameters.dat\fP file). If it does not find it, it will report it to standard output and in the log file. The .gsf file contains the bathymetric edits obtained from data cleaning using CARIS HIPS & SIPS.

.TP
.B \-D
\fIcolortable\fP
.br
Creates a digital terrain model (DTM) using the \fIcolortable\fP color table. The color table must have been generated by QGIS or use the equivalent format. See section \fBSpecifying a Color Table\fP below.

.TP
.B \-E
\fIdatalist\fP
.br
Creates \fBArcticNet Basemap\fP tiles of 15' latitude x 30' longitude in ESRI EHdr (.hdr) format from the specified \fBdatalist\fP. For each tile, four files will be generated:
    - a .flt binary file,
    - a .hdr ASCII header file,
    - a .prj ASCII header file containing the projection as WKT,
    - a .mb-1 ASCII file containing the filenames of the survey lines that are part of the tile.

.TP
.B \-H
This "help" flag cause the program to print out a description of its operation and then exit immediately.

.TP
.B \-M
\fIdatalist\fP
.br
Creates \fBGMT\fP bash shell scripts from the specified \fBdatalist\fP for each \fBArcticNet Basemap\fP of 15' latitude x 30' longitude. When executed, each script will produced a .ps (Postscript) and .gif map of the \fBArcticNet Basemap\fP of 15' latitude x 30' longitude. It is up to the user to modify the \fBGMT\fP script in order to produce an acceptable map.

.TP
.B \-P
\fIdatalist\fP
.br
This option is used to process the .mb59 \fBMB-System\fP data files to produce processed p.mb59 \fBMB-System\fP data files. Processed files have the following characteristics: 1) bathymetric edits have been applied in order to reject outlier soundings; 2) soundings have been reduced to \fBMean Sea Level\fP (assumed to be equivalent to CGVD2013) by the \fBWebTide\fP predicted tides; 3) a new sound velocity correction may have been applied to the soundings if the sound velocity profile used during data collection was deemed to be inaccurate.

.TP
.B \-T
\fInmeafile\fP
.br
Creates a shiptrack from the specified \fBNMEA_logger\fP file. \fBNMEA_logger\fP is a program developped by the University of New-Brunswick to parse NMEA data coming from the Amundsen's Applanix POS/MV 320 inertial navigation system. The \fBNMEA_logger\fP files must reside in the directory pointed to by the variable $NMEA (see \fIparameters.dat\fP file).

.TP
.B \-U
.br
Converts the .all files contained in the directory pointed to by the variable $DIR_DATA_ALL (see \fIparameters.dat\fP file) into .mb59 files and stores them into the directory pointed to by the variable $DIR_DATA_MB59 (see \fIparameters.dat\fP file). Only files found in the $DIR_DATA_ALL directory that have not yet been converted to .mb59 will be converted. Hence, the \fB-U\fP option is akin to an update to convert all new .all files present in the $DIR_DATA_ALL directory. Like with the \fB-C\fP option, for each .all file, the program will try to find a .gsf file with the same name in the directory pointed to by the variable $DIR_DATA_GSF (see \fIparameters.dat\fP file). If it does not find it, it will report it to standard output and in the log file. The .gsf file contains the bathymetric edits obtained from data cleaning using CARIS HIPS & SIPS.

.SH SPECIFYING A COLOR TABLE
TO BE COMPLETED

.SH BUGS
If I were a better programmer, no.

.SH AUTHOR
Jean-Guy Nistad (jgnistad@gmail.com)
